apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: consumidor-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
        flow: test
        layer: test
    spec:
      containers:
        - name: consumer-service
          image: consumer-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: LEGACY_URL
              value: "http://istio-ingressgateway.istio-system.svc.cluster.local/legacy/no-monetario"
            - name: TARGET_URL
              value: "http://common-service.transversales.svc.cluster.local"
            - name: COMMON_SERVICE_PATH
              value: "api/mci/labels"
            - name: API_BASE_PATH
              value: "/api/v1/test"
