apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-service
  template:
    metadata:
      labels:
        app: common-service
        flow: mnt
        layer: com
    spec:
      containers:
        - name: common-service
          image: common-service:latest
          imagePullPolicy: Never
          env:
            - name: POD_LABEL_FLOW
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['flow']
            - name: POD_LABEL_LAYER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['layer']
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"